INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Alexander', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Americano', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Angel Face', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Aviation', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Between the Sheets', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Boulevardier', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Brandy Crusta', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Casino', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Clover Club', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Daiquiri', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dry Martini', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Fizz', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hanky Panky', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('John Collins', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Last Word', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Manhattan', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Martinez', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mary Pickford', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Monkey Gland', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Negroni', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Fashioned', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paradise', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Planters Punch', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porto Flip', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Ramos Fizz', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Remember the Maine', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Rusty Nail', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sazerac', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sidecar', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Stinger', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tuxedo', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Vieux Carre', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Whiskey Sour', 1);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('White Lady', 1);

INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bellini', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Black Russian', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bloody Mary', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Caipirinha', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cardinale', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Champagne Cocktail', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Corpse Reviver No.2', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cosmopolitan', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cuba Libre', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French 75', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Connection', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Garibaldi', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grasshopper', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hemingway Special', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Horse''s Neck', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Irish Coffee', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Kir', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Lemon Drop Martini', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Long Island Iced Tea', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mai Tai', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Margarita', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mimosa', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mint Julep', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mojito', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Moscow Mule', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pina Colada', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Sour', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Rabo de Galo', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sea Breeze', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sex on the Beach', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Singapore Sling', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tequila Sunrise', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Vesper', 2);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Zombie', 2);

INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bee''s Knees', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bramble', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Canchanchara', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Chartreuse Swizzle', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dark ''N'' Stormy', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Don''s Special Daiquiri', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Espresso Martini', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Fernandito', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Martini', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Basil Smash', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grand Margarita', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('IBA Tiki', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Illegal', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Jungle Bird', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Missionary''s Downfall', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Naked and Famous', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('New York Sour', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Cuban', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paloma', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paper Plane', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Penicillin', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Punch', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porn Star Martini', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Russian Spring Punch', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sherry Cobbler', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('South Side', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Spicy Fifty', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Spritz', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Suffering Bastard', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Three Dots and a Dash', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tipperary', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tommy''s Margarita', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Trinidad Sour', 3);
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Ve.N.To', 3);

--Alexander--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Alexander', 4);  -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Alexander', 5);  -- 유서 깊음
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Alexander', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Alexander', 16); -- 부드러움

--Americano--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Americano', 8);  -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Americano', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Americano', 4);  -- 고급스러움

--Angel Face--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Angel Face', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Angel Face', 16); -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Angel Face', 18); -- 자극적

--Aviation--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Aviation', 16); -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Aviation', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Aviation', 4);  -- 고급스러움

--Bee's Knees--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bee''s Knees', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bee''s Knees', 16); -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bee''s Knees', 21);  -- 상큼함

--Bellini--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bellini', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bellini', 16); -- 부드러움

--Between the Sheets--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Between the Sheets', 17); -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Between the Sheets', 4);  -- 고급스러움

--Black Russian--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Black Russian', 17); -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Black Russian', 8);  -- 쓴 맛

--Bloody Mary--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bloody Mary', 11); -- 각성용
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bloody Mary', 18); -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bloody Mary', 17); -- 강함

--Boulevardier--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Boulevardier', 17); -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Boulevardier', 4);  -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Boulevardier', 8);  -- 쓴 맛

--Bloody Mary--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bramble', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bramble', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Bramble', 16); -- 부드러움

-- Brandy Crusta--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Brandy Crusta', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Brandy Crusta', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Brandy Crusta', 16); -- 부드러움

-- Caipirinha--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Caipirinha', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Caipirinha', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Caipirinha', 21);   -- 상큼함

-- Canchanchara--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Canchanchara', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Canchanchara', 16); -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Canchanchara', 18); -- 자극적

-- Cardinale--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cardinale', 4);  -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cardinale', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cardinale', 16); -- 부드러움

-- Casino--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Casino', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Casino', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Casino', 21);   -- 상큼함

-- Champagne Cocktail--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Champagne Cocktail', 4);  -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Champagne Cocktail', 7);  -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Champagne Cocktail', 16); -- 부드러움

-- Chartreuse Swizzle--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Chartreuse Swizzle', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Chartreuse Swizzle', 21);   -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Chartreuse Swizzle', 16);  -- 부드러움

-- Clover Club--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Clover Club', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Clover Club', 16); -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Clover Club', 7);  -- 달콤함

-- Corpse Reviver #2--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Corpse Reviver No.2', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Corpse Reviver No.2', 4);   -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Corpse Reviver No.2', 16);  -- 부드러움

-- Cosmopolitan--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cosmopolitan', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cosmopolitan', 4);  -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cosmopolitan', 16); -- 부드러움

-- Cuba Libre--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cuba Libre', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cuba Libre', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Cuba Libre', 16);  -- 부드러움

-- Daiquiri--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Daiquiri', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Daiquiri', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Daiquiri', 16);  -- 부드러움

-- Dark 'N' Stormy--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dark ''N'' Stormy', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dark ''N'' Stormy', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dark ''N'' Stormy', 18);  -- 자극적

-- Don's Special Daiquiri--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Don''s Special Daiquiri', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Don''s Special Daiquiri', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Don''s Special Daiquiri', 16);  -- 부드러움

-- Dry Martini--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dry Martini', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Dry Martini', 4);   -- 고급스러움

-- Espresso Martini--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Espresso Martini', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Espresso Martini', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Espresso Martini', 16);  -- 부드러움

-- Fernandito--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Fernandito', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Fernandito', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Fernandito', 16);  -- 부드러움

-- French 75--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French 75', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French 75', 4);   -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French 75', 16);  -- 부드러움

-- French Connection--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Connection', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Connection', 16);  -- 부드러움

-- French Martini--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Martini', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Martini', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('French Martini', 16);  -- 부드러움

-- Garibaldi--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Garibaldi', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Garibaldi', 8);   -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Garibaldi', 16);  -- 부드러움

-- Gin Basil Smash--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Basil Smash', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Basil Smash', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Basil Smash', 18);  -- 자극적

-- Gin Fizz--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Fizz', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Fizz', 13);  -- 거품 많음
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Gin Fizz', 16);  -- 부드러움

-- Grand Margarita--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grand Margarita', 4);  -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grand Margarita', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grand Margarita', 16);  -- 부드러움

-- Grasshopper--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grasshopper', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grasshopper', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Grasshopper', 19);  -- 여성적임

-- Hanky Panky--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hanky Panky', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hanky Panky', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hanky Panky', 16);  -- 부드러움

-- Hemingway Special--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hemingway Special', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hemingway Special', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Hemingway Special', 7);   -- 달콤함

-- Horse's Neck--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Horse''s Neck', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Horse''s Neck', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Horse''s Neck', 18);  -- 자극적

-- IBA Tiki--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('IBA Tiki', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('IBA Tiki', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('IBA Tiki', 16);  -- 부드러움

-- Illegal--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Illegal', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Illegal', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Illegal', 7);   -- 달콤함

-- Irish Coffee--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Irish Coffee', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Irish Coffee', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Irish Coffee', 13);  -- 거품 많음

-- John Collins--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('John Collins', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('John Collins', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('John Collins', 13);  -- 거품 많음

-- Jungle Bird--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Jungle Bird', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Jungle Bird', 4);   -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Jungle Bird', 16);  -- 부드러움

-- Kir--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Kir', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Kir', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Kir', 16);  -- 부드러움

-- Last Word--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Last Word', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Last Word', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Last Word', 18);  -- 자극적

-- Lemon Drop Martini--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Lemon Drop Martini', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Lemon Drop Martini', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Lemon Drop Martini', 16);  -- 부드러움

-- Long Island Iced Tea--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Long Island Iced Tea', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Long Island Iced Tea', 18);  -- 자극적
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Long Island Iced Tea', 21);  -- 상큼함

-- Mai Tai--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mai Tai', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mai Tai', 4);   -- 고급스러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mai Tai', 16);  -- 부드러움

-- Manhattan--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Manhattan', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Manhattan', 8);   -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Manhattan', 16);  -- 부드러움

-- Margarita--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Margarita', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Margarita', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Margarita', 7);   -- 달콤함

-- Martinez--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Martinez', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Martinez', 8);   -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Martinez', 16);  -- 부드러움

-- Mary Pickford--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mary Pickford', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mary Pickford', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mary Pickford', 16);  -- 부드러움

-- Mimosa--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mimosa', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mimosa', 16);  -- 부드러움

-- Mint Julep--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mint Julep', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mint Julep', 13);  -- 거품 많음
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mint Julep', 5);   -- 유서 깊음

-- Missionary's Downfall--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Missionary''s Downfall', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Missionary''s Downfall', 16);  -- 부드러움

-- Mojito--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mojito', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mojito', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Mojito', 13);  -- 거품 많음

-- Monkey Gland--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Monkey Gland', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Monkey Gland', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Monkey Gland', 18);  -- 자극적

-- Moscow Mule--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Moscow Mule', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Moscow Mule', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Moscow Mule', 18);  -- 자극적

-- Naked and Famous--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Naked and Famous', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Naked and Famous', 16);  -- 부드러움

-- Negroni--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Negroni', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Negroni', 8);   -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Negroni', 16);  -- 부드러움

-- New York Sour--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('New York Sour', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('New York Sour', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('New York Sour', 18);  -- 자극적

-- Old Cuban--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Cuban', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Cuban', 8);   -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Cuban', 14);  -- 화끈함

-- Old Fashioned--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Fashioned', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Fashioned', 8);   -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Old Fashioned', 16);  -- 부드러움

-- Paloma--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paloma', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paloma', 16);  -- 부드러움

-- Paper Plane--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paper Plane', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paper Plane', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paper Plane', 18);  -- 자극적

-- Paradise--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paradise', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paradise', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Paradise', 16);  -- 부드러움

-- Penicillin--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Penicillin', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Penicillin', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Penicillin', 18);  -- 자극적

-- Pina Colada--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pina Colada', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pina Colada', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pina Colada', 7);   -- 달콤함

-- Pisco Punch--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Punch', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Punch', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Punch', 18);  -- 자극적

-- Pisco Sour--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Sour', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Sour', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Pisco Sour', 7);   -- 달콤함

-- Planters Punch--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Planters Punch', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Planters Punch', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Planters Punch', 16);  -- 부드러움

-- Porn Star Martini--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porn Star Martini', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porn Star Martini', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porn Star Martini', 16);  -- 부드러움

-- Porto Flip--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porto Flip', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Porto Flip', 7);   -- 달콤함

-- Rabo de Galo--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Rabo de Galo', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Rabo de Galo', 8);   -- 쓴 맛

-- Ramos Fizz--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Ramos Fizz', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Ramos Fizz', 21);  -- 상큼함

-- Remember the Maine--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Remember the Maine', 16);  -- 부드러움
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Remember the Maine', 18);  -- 자극적

-- Russian Spring Punch--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Russian Spring Punch', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Russian Spring Punch', 16);  -- 부드러움

-- Rusty Nail--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Rusty Nail', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Rusty Nail', 7);   -- 달콤함

-- Sazerac--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sazerac', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sazerac', 8);   -- 쓴 맛

-- Sea Breeze--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sea Breeze', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sea Breeze', 16);  -- 부드러움

-- Sex on the Beach--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sex on the Beach', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sex on the Beach', 7);   -- 달콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sex on the Beach', 16);  -- 부드러움

-- Sherry Cobbler--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sherry Cobbler', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sherry Cobbler', 7);   -- 달콤함

-- Sidecar--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sidecar', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Sidecar', 8);   -- 쓴 맛

-- Singapore Sling--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Singapore Sling', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Singapore Sling', 16);  -- 부드러움

-- South Side--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('South Side', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('South Side', 20);  -- 허브향

-- Spicy Fifty--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Spicy Fifty', 19);  -- 매콤함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Spicy Fifty', 7);   -- 달콤함

-- Spritz--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Spritz', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Spritz', 16);  -- 부드러움

-- Stinger--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Stinger', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Stinger', 20);  -- 허브향

-- Suffering Bastard--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Suffering Bastard', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Suffering Bastard', 19);  -- 매콤함

-- Tequila Sunrise--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tequila Sunrise', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tequila Sunrise', 7);   -- 달콤함

-- Three Dots and a Dash--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Three Dots and a Dash', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Three Dots and a Dash', 7);   -- 달콤함

-- Tipperary--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tipperary', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tipperary', 8);   -- 쓴 맛

-- Tommy's Margarita--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tommy''s Margarita', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tommy''s Margarita', 16);  -- 부드러움

-- Trinidad Sour--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Trinidad Sour', 8);  -- 쓴 맛
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Trinidad Sour', 19);  -- 매콤함

-- Tuxedo--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tuxedo', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Tuxedo', 8);   -- 쓴 맛

-- Ve.N.To--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Ve.N.To', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Ve.N.To', 7);   -- 달콤함

-- Vesper--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Vesper', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Vesper', 8);   -- 쓴 맛

-- Vieux Carré--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Vieux Carre', 17);  -- 강함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Vieux Carre', 8);   -- 쓴 맛

-- Whiskey Sour--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Whiskey Sour', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Whiskey Sour', 16);  -- 부드러움

-- White Lady--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('White Lady', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('White Lady', 16);  -- 부드러움

-- Zombie--
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Zombie', 21);  -- 상큼함
INSERT INTO COCKTAIL_TAG (COCKTAIL_NAME, TAG_ID) VALUES ('Zombie', 19);  -- 매콤함
